package com.example.pda.util

object Constants {
    const val ACTION_BARCODE_OPEN: String = "kr.co.bluebird.android.bbapi.action.BARCODE_OPEN"
    const val ACTION_BARCODE_CLOSE: String = "kr.co.bluebird.android.bbapi.action.BARCODE_CLOSE"
    const val ACTION_BARCODE_SET_TRIGGER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_SET_TRIGGER"
    const val ACTION_BARCODE_CALLBACK_REQUEST_SUCCESS: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_REQUEST_SUCCESS"
    const val ACTION_BARCODE_CALLBACK_REQUEST_FAILED: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_REQUEST_FAILED"
    const val ACTION_BARCODE_CALLBACK_DECODING_DATA: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_DECODING_DATA"
    const val ACTION_BARCODE_SET_PARAMETER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_SET_PARAMETER"
    const val ACTION_BARCODE_GET_PARAMETER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_GET_PARAMETER"
    const val ACTION_BARCODE_CALLBACK_PARAMETER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_PARAMETER"
    const val ACTION_BARCODE_GET_STATUS: String = "kr.co.bluebird.android.action.BARCODE_GET_STATUS"
    const val ACTION_BARCODE_CALLBACK_GET_STATUS: String =
        "kr.co.bluebird.android.action.BARCODE_CALLBACK_GET_STATUS"


    const val EXTRA_BARCODE_DECODING_DATA: String = "EXTRA_BARCODE_DECODING_DATA"
    const val EXTRA_HANDLE: String = "EXTRA_HANDLE"
    const val EXTRA_INT_DATA2: String = "EXTRA_INT_DATA2"
    const val EXTRA_STR_DATA1: String = "EXTRA_STR_DATA1"
    const val EXTRA_INT_DATA3: String = "EXTRA_INT_DATA3"


    val ERROR_FAILED: Int = -1
    val ERROR_NOT_SUPPORTED: Int = -2
    val ERROR_NO_RESPONSE: Int = -4
    val ERROR_BATTERY_LOW: Int = -5
    val ERROR_BARCODE_DECODING_TIMEOUT: Int = -6
    val ERROR_BARCODE_ERROR_USE_TIMEOUT: Int = -7
    val ERROR_BARCODE_ERROR_ALREADY_OPENED: Int = -8
    val ERROR_BARCODE_EXCEED_ASCII_CODE: Int = -10

    const val STATUS_OPEN: String = "STATUS_OPEN"
    const val STATUS_CLOSE: String = "STATUS_CLOSE"
    const val STATUS_TRIGGER_ON: String = "STATUS_TRIGGER_ON"

    const val SEQ_BARCODE_OPEN: Int = 100
    const val SEQ_BARCODE_CLOSE: Int = 200
    const val SEQ_BARCODE_GET_STATUS: Int = 300
    const val SEQ_BARCODE_SET_TRIGGER_ON: Int = 400
    const val SEQ_BARCODE_SET_TRIGGER_OFF: Int = 500
    const val SEQ_BARCODE_SET_PARAMETER: Int = 600
    const val SEQ_BARCODE_GET_PARAMETER: Int = 700
}

// intent, broadcast 방식
object Constants2 {
    const val ACTION_BARCODE_OPEN: String = "kr.co.bluebird.android.bbapi.action.BARCODE_OPEN"
    const val ACTION_BARCODE_CLOSE: String = "kr.co.bluebird.android.bbapi.action.BARCODE_CLOSE"
    const val ACTION_BARCODE_SET_TRIGGER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_SET_TRIGGER"
    const val ACTION_BARCODE_CALLBACK_REQUEST_SUCCESS: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_REQUEST_SUCCESS"
    const val ACTION_BARCODE_CALLBACK_REQUEST_FAILED: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_REQUEST_FAILED"
    const val ACTION_BARCODE_CALLBACK_DECODING_DATA: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_DECODING_DATA"
    const val ACTION_BARCODE_SET_PARAMETER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_SET_PARAMETER"
    const val ACTION_BARCODE_GET_PARAMETER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_GET_PARAMETER"
    const val ACTION_BARCODE_CALLBACK_PARAMETER: String =
        "kr.co.bluebird.android.bbapi.action.BARCODE_CALLBACK_PARAMETER"
    const val ACTION_BARCODE_GET_STATUS: String = "kr.co.bluebird.android.action.BARCODE_GET_STATUS"
    const val ACTION_BARCODE_CALLBACK_GET_STATUS: String =
        "kr.co.bluebird.android.action.BARCODE_CALLBACK_GET_STATUS"


    const val EXTRA_BARCODE_DECODING_DATA: String = "EXTRA_BARCODE_DECODING_DATA"
    const val EXTRA_HANDLE: String = "EXTRA_HANDLE"
    const val EXTRA_INT_DATA2: String = "EXTRA_INT_DATA2"
    const val EXTRA_STR_DATA1: String = "EXTRA_STR_DATA1"
    const val EXTRA_INT_DATA3: String = "EXTRA_INT_DATA3"


    val ERROR_FAILED: Int = -1
    val ERROR_NOT_SUPPORTED: Int = -2
    val ERROR_NO_RESPONSE: Int = -4
    val ERROR_BATTERY_LOW: Int = -5
    val ERROR_BARCODE_DECODING_TIMEOUT: Int = -6
    val ERROR_BARCODE_ERROR_USE_TIMEOUT: Int = -7
    val ERROR_BARCODE_ERROR_ALREADY_OPENED: Int = -8
    val ERROR_BARCODE_EXCEED_ASCII_CODE: Int = -10
}


object BBAPI {
    //+Result
    const val BBAPI_SUCCESS: Int = 0
    val BBAPI_FAILED: Int = -1
    val BBAPI_NOT_SUPPORTED: Int = -2
    val BBAPI_ERROR_CHECKSUM: Int = -3
    val BBAPI_ERROR_NO_RESPONSE: Int = -4
    val BBAPI_BATTERY_LOW: Int = -5
    val BBAPI_ERROR_BARCODE_DECODING_TIMEOUT: Int = -6
    val BBAPI_ERROR_BARCODE_USE_TIMEOUT: Int = -7
    val BBAPI_ERROR_BARCODE_ALREADY_OPENED: Int = -8
    val BBAPI_ERROR_BARCODE_CAMERA_USED: Int = -9
    val BBAPI_ERROR_BARCODE_EXCEED_ASCII_CODE: Int = -10

    //Result+
    //+Barcode Mode
    const val BARCODE_MODE_PREFIX: Int = 500
    val BARCODE_MODE_SUFFIX: Int = BARCODE_MODE_PREFIX + 1
    val BARCODE_MODE_SOUND: Int = BARCODE_MODE_PREFIX + 2
    val BARCODE_MODE_TRIGGER: Int = BARCODE_MODE_PREFIX + 3
    val BARCODE_MODE_AIMER: Int = BARCODE_MODE_PREFIX + 4
    val BARCODE_MODE_ILLUMINATION: Int = BARCODE_MODE_PREFIX + 5
    val BARCODE_MODE_DECODE_TIMEOUT: Int = BARCODE_MODE_PREFIX + 6
    val BARCODE_MODE_SAME_SYMBOL_TIMEOUT: Int = BARCODE_MODE_PREFIX + 7

    val BARCODE_MODE_2DPQA: Int = BARCODE_MODE_PREFIX + 8
    val BARCODE_MODE_DECODE_CENTERING_WINDOW: Int = BARCODE_MODE_PREFIX + 9
    val BARCODE_MODE_DECODE_CENTERING_WINDOW_RECT: Int = BARCODE_MODE_PREFIX + 10
    val BARCODE_MODE_DECODE_OPTION: Int = BARCODE_MODE_PREFIX + 11
    val BARCODE_MODE_DECODE_OPTION_PRINTWEIGHT: Int = BARCODE_MODE_PREFIX + 12
    val BARCODE_MODE_DECODE_OPTION_DECODEMODE: Int = BARCODE_MODE_PREFIX + 13
    val BARCODE_MODE_DECODE_OPTION_LINEARRANGE: Int = BARCODE_MODE_PREFIX + 14
    val BARCODE_MODE_DECODE_OPTION_VIDEOREVERSE: Int = BARCODE_MODE_PREFIX + 15
    val BARCODE_MODE_DECODE_OPTION_DECATTEMPTLIMIT: Int = BARCODE_MODE_PREFIX + 16
    val BARCODE_MODE_DECODE_OPTION_SEARCHLIMIT: Int = BARCODE_MODE_PREFIX + 17
    val BARCODE_MODE_EXPOSURE: Int = BARCODE_MODE_PREFIX + 18
    val BARCODE_MODE_EXPOSURE_TYPE: Int = BARCODE_MODE_PREFIX + 19
    val BARCODE_MODE_EXPOSURE_SETTING: Int = BARCODE_MODE_PREFIX + 20
    val BARCODE_MODE_EXPOSURE_SETTING_EXPOSURE: Int = BARCODE_MODE_PREFIX + 21
    val BARCODE_MODE_EXPOSURE_SETTING_MAX: Int = BARCODE_MODE_PREFIX + 22
    val BARCODE_MODE_EXPOSURE_SETTING_TARGETWHITE: Int = BARCODE_MODE_PREFIX + 23
    val BARCODE_MODE_EXPOSURE_SETTING_TARGETWHITEWINDOW: Int = BARCODE_MODE_PREFIX + 24
    val BARCODE_MODE_EXPOSURE_SETTING_IMAGEMUSTCONFORM: Int = BARCODE_MODE_PREFIX + 25
    val BARCODE_MODE_EXPOSURE_SETTING_NUMUPDATES: Int = BARCODE_MODE_PREFIX + 26
    val BARCODE_MODE_EXPOSURE_SETTING_FRAMERATE: Int = BARCODE_MODE_PREFIX + 27
    val BARCODE_MODE_EXPOSURE_SETTING_SPECEXCLUSION: Int = BARCODE_MODE_PREFIX + 28
    val BARCODE_MODE_EXPOSURE_SETTING_SPECSATURATION: Int = BARCODE_MODE_PREFIX + 29
    val BARCODE_MODE_EXPOSURE_SETTING_SPECLIMIT: Int = BARCODE_MODE_PREFIX + 30
    val BARCODE_MODE_EXPOSURE_SETTING_FIXEDEXPOSURE: Int = BARCODE_MODE_PREFIX + 31
    val BARCODE_MODE_EXPOSURE_SETTING_FIXEDGAIN: Int = BARCODE_MODE_PREFIX + 32
    val BARCODE_MODE_EXPOSURE_SETTING_FIXEDFRAMERATE: Int = BARCODE_MODE_PREFIX + 33
    val BARCODE_MODE_LIGHTS: Int = BARCODE_MODE_PREFIX + 34
    val BARCODE_MODE_LIGHTS_TYPE: Int = BARCODE_MODE_PREFIX + 35
    val BARCODE_MODE_OCR: Int = BARCODE_MODE_PREFIX + 36
    val BARCODE_MODE_OCR_FONT: Int = BARCODE_MODE_PREFIX + 37
    val BARCODE_MODE_OCR_TEMPLATE: Int = BARCODE_MODE_PREFIX + 38
    val BARCODE_MODE_OCR_GROUP_G: Int = BARCODE_MODE_PREFIX + 39
    val BARCODE_MODE_OCR_GROUP_H: Int = BARCODE_MODE_PREFIX + 40
    val BARCODE_MODE_OCR_GROUP_CHAR: Int = BARCODE_MODE_PREFIX + 41
    val BARCODE_MODE_HANDED: Int = BARCODE_MODE_PREFIX + 42
    val BARCODE_MODE_POSTAMBLE: Int = BARCODE_MODE_PREFIX + 43
    val BARCODE_MODE_SUBAMBLE: Int = BARCODE_MODE_PREFIX + 44
    val BARCODE_MODE_DATA_WEDGE: Int = BARCODE_MODE_PREFIX + 45
    val BARCODE_MODE_USE_TIMEOUT: Int = BARCODE_MODE_PREFIX + 46
    val BARCODE_MODE_DATA_WEDGE_TYPE: Int = BARCODE_MODE_PREFIX + 47

    val BARCODE_MODE_PICKLIST: Int = BARCODE_MODE_PREFIX + 48
    val BARCODE_MODE_IMAGE_CROPPING: Int = BARCODE_MODE_PREFIX + 49
    val BARCODE_MODE_CROP_TO_PIXEL_ADDRESSES: Int = BARCODE_MODE_PREFIX + 50
    val BARCODE_MODE_IMAGE_RESOLUTION: Int = BARCODE_MODE_PREFIX + 51
    val BARCODE_MODE_IMAGE_FILE_FORMAT: Int = BARCODE_MODE_PREFIX + 52
    val BARCODE_MODE_IMAGE_BPP: Int = BARCODE_MODE_PREFIX + 53
    val BARCODE_MODE_IMAGE_CROPPING_PIXCEL_TOP: Int = BARCODE_MODE_PREFIX + 54
    val BARCODE_MODE_IMAGE_CROPPING_PIXCEL_LEFT: Int = BARCODE_MODE_PREFIX + 55
    val BARCODE_MODE_IMAGE_CROPPING_PIXCEL_BOTTOM: Int = BARCODE_MODE_PREFIX + 56
    val BARCODE_MODE_IMAGE_CROPPING_PIXCEL_RIGHT: Int = BARCODE_MODE_PREFIX + 57

    val BARCODE_MODE_IMAGE_FILE_PATH: Int = BARCODE_MODE_PREFIX + 58
    val BARCODE_MODE_IMAGE_CAPTURE_AIMER: Int = BARCODE_MODE_PREFIX + 59
    val BARCODE_MODE_IMAGE_CAPTURE_ILLUMINATION: Int = BARCODE_MODE_PREFIX + 60
    val BARCODE_MODE_ILLUMINATION_LEVEL: Int = BARCODE_MODE_PREFIX + 61
    val BARCODE_MODE_DATAWEDGE_INTENT_ACTION: Int = BARCODE_MODE_PREFIX + 70
    val BARCODE_MODE_DATAWEDGE_INTENT_ACTION_CATEGORY: Int = BARCODE_MODE_PREFIX + 71

    val BARCODE_MODE_MULTI_DECODE_MODE: Int = BARCODE_MODE_PREFIX + 72
    val BARCODE_MODE_MULTI_DECODE_BARCODE_TO_READ: Int = BARCODE_MODE_PREFIX + 73
    val BARCODE_MODE_MULTI_DECODE_FULL_READ_MODE: Int = BARCODE_MODE_PREFIX + 74

    val BARCODE_MODE_DATAWEDGE_INTENT_ACTION_EXTRA_NAME: Int = BARCODE_MODE_PREFIX + 75
    val SYMBOLOGY_REPLACE_FNC1: Int = BARCODE_MODE_PREFIX + 76
    val BARCODE_MODE_DATAWEDGE_KEYBOARD_TYPE: Int = BARCODE_MODE_PREFIX + 77
    val BARCODE_MODE_DATAWEDGE_DECODING_TYPE: Int = BARCODE_MODE_PREFIX + 78

    //Barcode Mode+
    //+Barcode Symbology
    const val SYMBOLOGY_UPC_A: Int = 1
    const val SYMBOLOGY_UPC_E: Int = 2
    const val SYMBOLOGY_UPC_E1: Int = 3
    const val SYMBOLOGY_EAN8: Int = 4
    const val SYMBOLOGY_EAN13: Int = 5
    const val SYMBOLOGY_BOOKLAND: Int = 6
    const val SYMBOLOGY_SUPPLEMENTAL_CODE: Int = 7
    const val SYMBOLOGY_CODE39: Int = 8
    const val SYMBOLOGY_CODE93: Int = 9
    const val SYMBOLOGY_CODE128: Int = 10
    const val SYMBOLOGY_INTERLEAVED2OF5: Int = 11
    const val SYMBOLOGY_CODABAR: Int = 12
    const val SYMBOLOGY_CODE11: Int = 13
    const val SYMBOLOGY_MSI: Int = 14
    const val SYMBOLOGY_GS1: Int = 15
    const val SYMBOLOGY_PDF417: Int = 16
    const val SYMBOLOGY_ISBT128: Int = 17
    const val SYMBOLOGY_COMPOSITE_CC_C: Int = 18
    const val SYMBOLOGY_MATRIX2OF5: Int = 19
    const val SYMBOLOGY_DATAMATRIX: Int = 20
    const val SYMBOLOGY_MAXICODE: Int = 21
    const val SYMBOLOGY_AZTECCODE: Int = 22
    const val SYMBOLOGY_MICROPDF: Int = 23
    const val SYMBOLOGY_QRCODE: Int = 24
    const val SYMBOLOGY_TRIOPTIC_CODE: Int = 25
    const val SYMBOLOGY_DISCRETE2OF5: Int = 26
    const val SYMBOLOGY_USPS4CB: Int = 27
    const val SYMBOLOGY_AUSTRALIA_POST: Int = 28
    const val SYMBOLOGY_UK_POST: Int = 29
    const val SYMBOLOGY_CHINESE_POST: Int = 30
    const val SYMBOLOGY_JAPANESE_POST: Int = 31
    const val SYMBOLOGY_NETHERLANDS_POST: Int = 32
    const val SYMBOLOGY_KOREAN_POST: Int = 33
    const val SYMBOLOGY_US_POSTNET: Int = 34
    const val SYMBOLOGY_US_PLANET: Int = 35

    const val SYMBOLOGY_UPC_A_PREAMBLE: Int = 36
    const val SYMBOLOGY_UPC_A_TRANSMIT_CHECK_DIGIT: Int = 37
    const val SYMBOLOGY_UPC_E_PREAMBLE: Int = 38
    const val SYMBOLOGY_UPC_E_TRANSMIT_CHECK_DIGIT: Int = 39
    const val SYMBOLOGY_UPC_E1_PREAMBLE: Int = 40
    const val SYMBOLOGY_UPC_E1_TRANSMIT_CHECK_DIGIT: Int = 41
    const val SYMBOLOGY_EAN8_EXTEND: Int = 42
    const val SYMBOLOGY_EAN_TRANSMIT_ISSN: Int = 43
    const val SYMBOLOGY_BOOKLAND_ISBN: Int = 44
    const val SYMBOLOGY_SUPPLEMENTAL_REDUNDANCY: Int = 45
    const val SYMBOLOGY_SUPPLEMENTAL_AIM_ID: Int = 46
    const val SYMBOLOGY_CODE39_LENGTH_MIN: Int = 47
    const val SYMBOLOGY_CODE39_LENGTH_MAX: Int = 48
    const val SYMBOLOGY_CODE39_CHECK_DIGIT: Int = 49
    const val SYMBOLOGY_CODE39_TRANSMIT_CHECK_DIGIT: Int = 50
    const val SYMBOLOGY_CODE39_FULL_ASCII: Int = 51
    const val SYMBOLOGY_CODE93_LENGTH_MIN: Int = 52
    const val SYMBOLOGY_CODE93_LENGTH_MAX: Int = 53
    const val SYMBOLOGY_CODE128_LENGTH_MIN: Int = 54
    const val SYMBOLOGY_CODE128_LENGTH_MAX: Int = 55
    const val SYMBOLOGY_CODE128_EMULATION: Int = 56
    const val SYMBOLOGY_INTERLEAVED2OF5_LENGTH_MIN: Int = 57
    const val SYMBOLOGY_INTERLEAVED2OF5_LENGTH_MAX: Int = 58
    const val SYMBOLOGY_INTERLEAVED2OF5_CHECK_DIGIT: Int = 59
    const val SYMBOLOGY_INTERLEAVED2OF5_TRANSMIT_CHECK_DIGIT: Int = 60
    const val SYMBOLOGY_CODABAR_LENGTH_MIN: Int = 61
    const val SYMBOLOGY_CODABAR_LENGTH_MAX: Int = 62
    const val SYMBOLOGY_CODABAR_CLSI_EDITING: Int = 63
    const val SYMBOLOGY_CODABAR_NOTIS_EDITING: Int = 64
    const val SYMBOLOGY_CODE11_LENGTH_MIN: Int = 65
    const val SYMBOLOGY_CODE11_LENGTH_MAX: Int = 66
    const val SYMBOLOGY_CODE11_CHECK_DIGIT: Int = 67
    const val SYMBOLOGY_CODE11_TRANSMIT_CHECK_DIGIT: Int = 68
    const val SYMBOLOGY_MSI_LENGTH_MIN: Int = 69
    const val SYMBOLOGY_MSI_LENGTH_MAX: Int = 70
    const val SYMBOLOGY_MSI_CHECK_DIGIT: Int = 71
    const val SYMBOLOGY_MSI_TRANSMIT_CHECK_DIGIT: Int = 72
    const val SYMBOLOGY_MSI_CHECK_DIGIT_ALGORITHM: Int = 73
    const val SYMBOLOGY_GS1_LIMITED: Int = 74
    const val SYMBOLOGY_GS1_LIMITED_SECURITY_LEVEL: Int = 75
    const val SYMBOLOGY_ISBT128_CONCATENATION: Int = 76
    const val SYMBOLOGY_ISBT128_CHECK_TABLE: Int = 77
    const val SYMBOLOGY_ISBT128_CONCATENATION_REDUNDANCY: Int = 78
    const val SYMBOLOGY_MATRIX2OF5_LENGTH_MIN: Int = 79
    const val SYMBOLOGY_MATRIX2OF5_LENGTH_MAX: Int = 80
    const val SYMBOLOGY_MATRIX2OF5_SUPPLEMENTAL_REDUNDANCY: Int = 81
    const val SYMBOLOGY_MATRIX2OF5_CHECK_DIGIT: Int = 82
    const val SYMBOLOGY_MATRIX2OF5_TRANSMIT_CHECK_DIGIT: Int = 83
    const val SYMBOLOGY_COMPOSITE_CC_AB: Int = 84
    const val SYMBOLOGY_COMPOSITE_TLC_39: Int = 85
    const val SYMBOLOGY_COMPOSITE_UPC: Int = 86
    const val SYMBOLOGY_DATAMATRIX_INVERSE: Int = 87
    const val SYMBOLOGY_DATAMATRIX_ONLY: Int = 88
    const val SYMBOLOGY_DISCRETE2OF5_LENGTH_MIN: Int = 89
    const val SYMBOLOGY_DISCRETE2OF5_LENGTH_MAX: Int = 90
    const val SYMBOLOGY_US_TRANSMIT_CHECK_DIGIT: Int = 91
    const val SYMBOLOGY_QRCODE_INVERSE: Int = 92
    const val SYMBOLOGY_SPECIFIC_SECURITY: Int = 93
    const val SYMBOLOGY_SPECIFIC_INTERCHARACTER: Int = 94
    const val SYMBOLOGY_COUPON_REPORT: Int = 95
    const val SYMBOLOGY_CONVERT_UPCE_TO_A: Int = 96
    const val SYMBOLOGY_CONVERT_UPCE1_TO_A: Int = 97
    const val SYMBOLOGY_CONVERT_CODE39_TO_32: Int = 98
    const val SYMBOLOGY_CONVERT_I2OF5_TO_EAN13: Int = 99
    const val SYMBOLOGY_CONVERT_GS1_TO_UPCEAN: Int = 100
    const val SYMBOLOGY_GS1_DATABAR_EXPANDED: Int = 101
    const val SYMBOLOGY_GS1_128_EMULATION_FOR_UCC_COMPOSITE_CODE: Int = 102
    const val SYMBOLOGY_INVERSE_1D: Int = 103
    const val SYMBOLOGY_UPU_FICS_POSTAL: Int = 104
    const val SYMBOLOGY_UPC_COMPOSITE_MODE: Int = 105
    const val SYMBOLOGY_AZTEC_INVERSE: Int = 106
    const val SYMBOLOGY_SPECIFIC_REDUNDANCY_LEVEL: Int = 107
    const val SYMBOLOGY_AUSTRALIA_POST_FORMAT: Int = 108
    const val SYMBOLOGY_TRANSMIT_UK_POST_CHECK_DIGIT: Int = 109
    const val SYMBOLOGY_CODE32_PREFIX: Int = 110
    const val SYMBOLOGY_USER_SUPPLEMENTAL_1: Int = 111
    const val SYMBOLOGY_USER_SUPPLEMENTAL_2: Int = 112
    const val SYMBOLOGY_MICROQR: Int = 113

    const val SYMBOLOGY_CODE49: Int = 114
    const val SYMBOLOGY_OCR: Int = 115
    const val SYMBOLOGY_CANADIAN_POST: Int = 116
    const val SYMBOLOGY_IATA25: Int = 117
    const val SYMBOLOGY_TLCODE39: Int = 118
    const val SYMBOLOGY_CODE32: Int = 119
    const val SYMBOLOGY_STRAIGHT2OF5: Int = 120

    //public static final int SYMBOLOGY_PLESSEY								= 121;
    const val SYMBOLOGY_TELEPEN: Int = 122
    const val SYMBOLOGY_CODE16K: Int = 123
    const val SYMBOLOGY_POSI_CODE: Int = 124
    const val SYMBOLOGY_IDTAG: Int = 125
    const val SYMBOLOGY_LABEL4: Int = 126
    const val SYMBOLOGY_LABEL5: Int = 127
    const val SYMBOLOGY_GS1_128: Int = 128
    const val SYMBOLOGY_NUMBER: Int = 129
    const val SYMBOLOGY_ALL: Int = 130
    const val SYMBOLOGY_CODABLOCK: Int = 131
    const val SYMBOLOGY_RSS14: Int = 132
    const val SYMBOLOGY_CHINESE_2OF5: Int = 133

    const val SYMBOLOGY_HANXIN: Int = 134
    const val SYMBOLOGY_HANXIN_INVERSE: Int = 135
    const val SYMBOLOGY_IATA: Int = 136
    const val SYMBOLOGY_EAN128: Int = 137
    const val SYMBOLOGY_UPC_D: Int = 138
    const val SYMBOLOGY_GS1_DATABAR: Int = 139
    const val SYMBOLOGY_SCANLET: Int = 140
    const val SYMBOLOGY_CUECODE: Int = 141
    const val SYMBOLOGY_SIGNATURE_CAPTURE: Int = 142

    //	+newland
    const val SYMBOLOGY_AIM_128: Int = 143
    const val SYMBOLOGY_EAN_UCC_COMPOSITE: Int = 144
    const val SYMBOLOGY_UPC_EAN_COMPOSITE: Int = 145
    const val SYMBOLOGY_CODE39_START_STOP: Int = 146
    const val SYMBOLOGY_CODABAR_CHECK_DIGIT: Int = 147
    const val SYMBOLOGY_CODABAR_START_STOP: Int = 148
    const val SYMBOLOGY_GS1_DATABAR_AI: Int = 149
    const val SYMBOLOGY_INDUSTRIAL_25: Int = 150
    const val SYMBOLOGY_INDUSTRIAL_25_LENGTH_MIN: Int = 151
    const val SYMBOLOGY_INDUSTRIAL_25_LENGTH_MAX: Int = 152
    const val SYMBOLOGY_INDUSTRIAL_25_CHECK_DIGIT: Int = 153
    const val SYMBOLOGY_STANDARD_25: Int = 154
    const val SYMBOLOGY_STANDARD_25_LENGTH_MIN: Int = 155
    const val SYMBOLOGY_STANDARD_25_LENGTH_MAX: Int = 156
    const val SYMBOLOGY_STANDARD_25_CHECK_DIGIT: Int = 157
    const val SYMBOLOGY_PLESSEY: Int = 158
    const val SYMBOLOGY_PLESSEY_LENGTH_MIN: Int = 159
    const val SYMBOLOGY_PLESSEY_LENGTH_MAX: Int = 160
    const val SYMBOLOGY_PLESSEY_CHECK_DIGIT: Int = 161
    const val SYMBOLOGY_CHINESE_SENSIBLE_CODE: Int = 162
    const val SYMBOLOGY_OCR_B: Int = 163
    const val SYMBOLOGY_UPC_E_EXPAND_TO_UPC_A: Int = 164

    //	newland+
    const val SYMBOLOGY_EAN8_TRANSMIT_CHECK_DIGIT: Int = 165
    const val SYMBOLOGY_EAN13_TRANSMIT_CHECK_DIGIT: Int = 166 //Barcode Symbology+
}